name: gnome-mines
version: git
summary: Clear hidden mines from a minefield
description: |
  GNOME Mines is a puzzle game where you search for hidden mines. Flag the
  spaces with mines as quickly as possible to make the board a safer place. You
  win the game when you’ve flagged every mine on the board. Be careful not to
  trigger one, or the game is over!

  You can select the size of the field you want to play on at the start of the
  game. If you get stuck, you can ask for a hint: there’s a time penalty, but
  that’s better than hitting a mine!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-3.0+
  title: GNOME Mines

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-mines:
    interface: dbus
    bus: session
    name: org.gnome.mines

apps:
  gnome-mines:
    command: desktop-launch gnome-mines
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - unity7
      - wayland
    desktop: usr/share/applications/gnome-mines.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

parts:
  gnome-mines:
    build-attributes: [no-system-libraries]
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    override-build: |
      sed -i.bak -e 's|=gnome-mines$|=${SNAP}/meta/gui/gnome-mines.png|g' data/gnome-mines.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/256x256/gnome-mines.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/gnome-mines/current/usr/share/applications/gnome-mines.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-mines/current/usr]
    organize:
      snap/gnome-mines/current/usr: usr
    build-packages:
      - gettext
      - itstool
      - libglib2.0-dev
      - libgnome-games-support-1-dev
      - libgtk-3-dev
      - librsvg2-dev
      - libxml2-utils
      - valac
  libraries:
    plugin: nil
    stage-packages:
      - libgnome-games-support-1-2
      - libgee-0.8-2
    prime:
      - "usr/lib/*/libgnome-games-support-1.so.*"
      - "usr/lib/x86_64-linux-gnu/libgee-0.8.so.*"
